### ISSUE TITLE
user variable for region

### ISSUE THREAD

**Issue by 0xtf** [wata727/packer-post-processor-amazon-ami-management#19]
Hi again @wata727 

I'm trying to run the post-processor with a user variable, as such:

> "post-processors":[{
>      "type": "amazon-ami-management",
>      "region": "{{user `destination_regions`}}",
>      "identifier": "buildX",
>      "keep_releases": "1"
>     }
>    ]

destination_regions is defined as:

> {
>   "variables": {
>     "aws_access_key": "{{env `AWS_ACCESS_KEY_ID`}}",
>     "aws_secret_key": "{{env `AWS_SECRET_ACCESS_KEY`}}",
>     "destination_regions": "eu-west-1,eu-west-2,eu-west-3,eu-central-1,us-east-1,us-west-1,ap-northeast-1,sa-east-1",
>     "hostname": "buildXX"
>  },

I'm under the impression, however, that the post-processor cannot recognize this syntax and silently fails. Can that be the case? 

Any tips on how I can make use of a variable in your post-processor part? 

Thank you!

**Comment by 0xtf** [comment]
The title of my issue summarizes it. The proper definition is region**s**. I'm giving it a try now with region**s** and with the user variables.

**Comment by wata727** [comment]
Hi @0xtf, I confirmed this problem.
I think this post-processor should validate configurations more. For example, if `regions` is empty, it outputs the error message as follows:

```
$ packer build template.json
amazon-ebs output will be in this color.

Empty `regions` is not allowed. Please make sure that it is set correctly.
```

It has been confirmed that this behavior can be implemented as the packer plugin system. What do you think?

**Comment by 0xtf** [comment]
Hi @wata727,

Thank you for your excellent support and assistance, as always! 

The problem was in fact with the region/regions. Truth be told, the documentation makes it very clear that it should be **regions**. The only reason I had a problem was because I was coming from an older version of the plugin.

That being said, if you can add that confirmation/verification without too much work, I think it is a good thing.
