### ISSUE TITLE
Dry Run

### ISSUE THREAD

**Issue by nitrocode** [wata727/packer-post-processor-amazon-ami-management#25]
Thank you for putting the time in to make this post processor. I saw it in the [Packer Book on page 121](https://books.google.com/books?id=t9ksDwAAQBAJ&pg=PA121&lpg=PA121&dq=post+processor+amazon+ami+management+packer&source=bl&ots=dej55smwO7&sig=ACfU3U35EkfUtX5jhgqxGmwQDOSc13SWYA&hl=en&sa=X&ved=2ahUKEwjagqObhdbgAhVxoFkKHaF6BoIQ6AEwCXoECAEQAQ#v=onepage&q=post%20processor%20amazon%20ami%20management%20packer&f=false)!

It would be nice to have a dry run feature to print what the post processor would remove if it was enabled.

**Comment by wata727** [comment]
Thanks for your feedback. That makes sense. I'll work on it.

**Comment by nitrocode** [comment]
Wow that was fast!
