### ISSUE TITLE
Keep AMIs for the last X days

### ISSUE THREAD

**Issue by nitrocode** [wata727/packer-post-processor-amazon-ami-management#27]
Thanks a lot for the last one! This probably falls under "give an inch and they'll take a mile" but one more feature request. It would be nice to keep the AMIs for a number of days instead of (or in addition to) the number of images. 

For instance

```
  "post-processors":[{
    "type": "amazon-ami-management",
    "regions": ["us-east-1"],
    "identifier": "packer-example",
    "keep_releases": "30"
  }]
```

^ keep the last 30 releases

or

```
  "post-processors":[{
    "type": "amazon-ami-management",
    "regions": ["us-east-1"],
    "identifier": "packer-example",
    "keep_releases_for": "90"
  }]
```

^ keep releases created within the last 90 days

Thanks again!

**Comment by wata727** [comment]
Don't worry about that. I'm pleased to be able to listen to the voice of users.
Your feature request is reasonable and looks good. I'm planning to add this option as `keep_days`.

**Comment by nitrocode** [comment]
Great! This query syntax may be of help to you

    aws ec2 describe-instances --query 'Reservations[].Instances[?LaunchTime>=`2015-03-01`][].{id: InstanceId, type: InstanceType, launched: LaunchTime}'

Source: https://serverfault.com/a/708096/320458

**Comment by nitrocode** [comment]
Sweet! Thanks @wata727
