### ISSUE TITLE
Post-processor failed: unexpected EOF

### ISSUE THREAD

**Issue by awscodedeploy** [wata727/packer-post-processor-amazon-ami-management#3]
Hello,

As, i want to manage the AWS AMI retention, and after some research i came across this plugin, versions of packer and plugin are given below, but while executing the packer build command, at the stage of post processor [amazon-ami-management], unexpected EOF error is coming:

**Version:**
1. Packer V1.0.0
2. Packer post processor ami management V0.1.1

**Packer configuration:**
{
  "description": "Amazon AMI's",
  "builders": [{
    "type": "amazon-ebs",
    "region":  "ap-southeast-1" ,
    "vpc_id": "vpc-XXXXXXX",
   "subnet_id": "subnet-XXXXXX",
    "security_group_id": "sg-XXXXXXX",
    "source_ami": "ami-XXXXXXX",
    "instance_type": "t2.micro",
    "ssh_username": "ec2-user",
    "ami_name": "packer-example-{{timestamp}}",
    "tags": {
        "Amazon_AMI_Management_Identifier": "packer-example"
    }
  }
],
  "post-processors":[{
    "type": "amazon-ami-management",
    "region": "ap-southeast-1",
    "identifier": "packer-example",
    "keep_releases": "2"
  }]
}

**Packer build logs:**
amazon-ebs output will be in this color.

==> amazon-ebs: Prevalidating AMI Name...
    amazon-ebs: Found Image ID: ami-2c95344f
==> amazon-ebs: Creating temporary keypair: packer_59214322-e1a5-b9ee-6d94-250b2e1e2841
==> amazon-ebs: Launching a source AWS instance...
    amazon-ebs: Instance ID: i-0f06fbaa1ca05c7f9
==> amazon-ebs: Waiting for instance (i-0f06fbaa1ca05c7f9) to become ready...
==> amazon-ebs: Adding tags to source instance
    amazon-ebs: Adding tag: "Name": "Packer Builder"
==> amazon-ebs: Waiting for SSH to become available...
==> amazon-ebs: Connected to SSH!
==> amazon-ebs: Stopping the source instance...
==> amazon-ebs: Waiting for the instance to stop...
==> amazon-ebs: Creating the AMI: packer-example-1495352098
    amazon-ebs: AMI: ami-bf1691dc
==> amazon-ebs: Waiting for AMI to become ready...
^[[6~==> amazon-ebs: Adding tags to AMI (ami-bf1691dc)...
==> amazon-ebs: Tagging snapshot: snap-0b8c8ac4344792751
==> amazon-ebs: Creating AMI tags
    amazon-ebs: Adding tag: "Amazon_AMI_Management_Identifier": "packer-example"
==> amazon-ebs: Creating snapshot tags
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: No volumes to clean up, skipping
==> amazon-ebs: Deleting temporary keypair...
==> amazon-ebs: Running post-processor: amazon-ami-management
Build 'amazon-ebs' errored: 1 error(s) occurred:

* Post-processor failed: unexpected EOF

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: 1 error(s) occurred:

* Post-processor failed: unexpected EOF

==> Builds finished but no artifacts were created.

**Error:**
![image](https://cloud.githubusercontent.com/assets/12079189/26282085/6dbc3da4-3e27-11e7-85e3-dc141bcb1499.png)

Please let me know about this issue, what could be root cause for this?

Thanks in advance.

Regards,
Sandeep

**Comment by awscodedeploy** [comment]
Also, let me know if anything else is required from my side to debug this issue.

**Comment by wata727** [comment]
Hi @awscodedeploy, Thanks for your reports.
I tried this plugin with Packer v1.0.0, but there was no problem in my environments.

At first, please enable debug and output the debug log about this plugin. It can be controlled by  `PACKER_LOG` environment variable.
```
$ PACKER_LOG=1 packer build template.json
...
2017/05/21 21:42:22 ui: ==> amazon-ebs: Running post-processor: amazon-ami-management
==> amazon-ebs: Running post-processor: amazon-ami-management
2017/05/21 21:42:22 packer-post-processor-amazon-ami-management: 2017/05/21 21:42:22 Running Amazon AMI Management post-processor
2017/05/21 21:42:22 packer-post-processor-amazon-ami-management: 2017/05/21 21:42:22 Creating AWS session
2017/05/21 21:42:22 packer-post-processor-amazon-ami-management: 2017/05/21 21:42:22 Describing images for generation management
...
```

Next, please tell me about the AMI ID. If you can not do it, please tell me about the AMI's architecture, virtualization-type and platform etc. as much as possible.

**Comment by awscodedeploy** [comment]
Hi,

Thanks for the update, find the below packer build l;ogs:

**In terms of installation of amazon-ami-management packer plugin:**
1. i have downloaded the archive using below url respective to my system distro and architecture.
(https://github.com/wata727/packer-post-processor-amazon-ami-management/releases)
2. unzip the archive and copy the binary into the PATH
3. Let me know if i am doing wrong.

**AMI information:**
AMI ID: ami-2c95344f
Region: Singapore
Virtualization: HVM
Platform: Redhat Linux

**Packer build debug logs:**
==> amazon-ebs: Running post-processor: amazon-ami-management
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: 2017/05/21 13:45:29 Running Amazon AMI Management post-processor
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: 2017/05/21 13:45:29 Creating AWS session
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: 2017/05/21 13:45:29 Describing images for generation management
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: panic: runtime error: invalid memory address or nil pointer dereference
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: [signal 0xb code=0x1 addr=0x0 pc=0x93ee60]
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: 
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: goroutine 36 [running]:
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: panic(0xb9de80, 0xc82000a100)
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: 	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: github.com/aws/aws-sdk-go/aws/ec2metadata.(*EC2Metadata).GetMetadata(0x0, 0xdb1620, 0x19, 0x0, 0x0, 0x0, 0x0)
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: 	/Users/watanabekazuma/workspace/golang/src/github.com/aws/aws-sdk-go/aws/ec2metadata/api.go:18 +0x1b0
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds.requestCredList(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: 	/Users/watanabekazuma/workspace/golang/src/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds/ec2_role_provider.go:129 +0x74
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds.(*EC2RoleProvider).Retrieve(0xc82019af00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: 	/Users/watanabekazuma/workspace/golang/src/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds/ec2_role_provider.go:86 +0x7b
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: github.com/aws/aws-sdk-go/aws/credentials.(*ChainProvider).Retrieve(0xc82019af30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: 	/Users/watanabekazuma/workspace/golang/src/github.com/aws/aws-sdk-go/aws/credentials/chain_provider.go:67 +0xf2
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: github.com/aws/aws-sdk-go/aws/credentials.(*Credentials).Get(0xc820017220, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: 	/Users/watanabekazuma/workspace/golang/src/github.com/aws/aws-sdk-go/aws/credentials/credentials.go:182 +0x111
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: github.com/aws/aws-sdk-go/private/signer/v4.(*signer).sign(0xc82007b2b0, 0x0, 0x0)
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: 	/Users/watanabekazuma/workspace/golang/src/github.com/aws/aws-sdk-go/private/signer/v4/v4.go:123 +0x3bf
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: github.com/aws/aws-sdk-go/private/signer/v4.Sign(0xc82019d600)
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: 	/Users/watanabekazuma/workspace/golang/src/github.com/aws/aws-sdk-go/private/signer/v4/v4.go:97 +0x1e9
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run(0xc82019d718, 0xc82019d600)
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: 	/Users/watanabekazuma/workspace/golang/src/github.com/aws/aws-sdk-go/aws/request/handlers.go:115 +0x9f
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: github.com/aws/aws-sdk-go/aws/request.(*Request).Sign(0xc82019d600, 0x0, 0x0)
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: 	/Users/watanabekazuma/workspace/golang/src/github.com/aws/aws-sdk-go/aws/request/request.go:197 +0xce
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: github.com/aws/aws-sdk-go/aws/request.(*Request).Send(0xc82019d600, 0x0, 0x0)
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: 	/Users/watanabekazuma/workspace/golang/src/github.com/aws/aws-sdk-go/aws/request/request.go:207 +0x60
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: github.com/aws/aws-sdk-go/service/ec2.(*EC2).DescribeImages(0xc820028190, 0xc8201aecb0, 0xc820014260, 0x0, 0x0)
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: 	/Users/watanabekazuma/workspace/golang/src/github.com/aws/aws-sdk-go/service/ec2/api.go:3124 +0x4f
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: github.com/wata727/packer-post-processor-amazon-ami-management/plugin.(*PostProcessor).PostProcess(0xc8200141e0, 0x7fa0161af7b0, 0xc82011bce0, 0x7fa0161af7f8, 0xc82011bd00, 0x0, 0x0, 0xc81fff3292, 0x0, 0x0)
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: 	/Users/watanabekazuma/workspace/golang/src/github.com/wata727/packer-post-processor-amazon-ami-management/plugin/post-processor.go:74 +0x72b
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: github.com/mitchellh/packer/packer/rpc.(*PostProcessorServer).PostProcess(0xc82011ad60, 0x0, 0xc8201b0640, 0x0, 0x0)
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: 	/Users/watanabekazuma/workspace/golang/src/github.com/mitchellh/packer/packer/rpc/post_processor.go:83 +0x2ed
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: reflect.Value.call(0xb534c0, 0xbbd748, 0x13, 0xd00cd8, 0x4, 0xc82007bed8, 0x3, 0x3, 0x0, 0x0, ...)
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: 	/usr/local/Cellar/go/1.6/libexec/src/reflect/value.go:435 +0x120d
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: reflect.Value.Call(0xb534c0, 0xbbd748, 0x13, 0xc82007bed8, 0x3, 0x3, 0x0, 0x0, 0x0)
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: 	/usr/local/Cellar/go/1.6/libexec/src/reflect/value.go:303 +0xb1
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: net/rpc.(*service).call(0xc8201186c0, 0xc820118680, 0xc8200d2c90, 0xc820056d80, 0xc82011afc0, 0xa5f040, 0xc8201b045c, 0x18a, 0xa16fc0, 0xc8201b0640, ...)
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: 	/usr/local/Cellar/go/1.6/libexec/src/net/rpc/server.go:383 +0x1c2
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: created by net/rpc.(*Server).ServeCodec
2017/05/21 13:45:29 packer-post-processor-amazon-ami-management: 	/usr/local/Cellar/go/1.6/libexec/src/net/rpc/server.go:477 +0x49d
2017/05/21 13:45:29 /data/hashicorp/packer/mcd/packer-post-processor-amazon-ami-management: plugin process exited
2017/05/21 13:45:29 Deleting original artifact for build 'amazon-ebs'
2017/05/21 13:45:29 hpacker: 2017/05/21 13:45:29 Deregistering image ID (ami-1a1e9979) from region (ap-southeast-1)
2017/05/21 13:45:30 ui error: Build 'amazon-ebs' errored: 1 error(s) occurred:

* Post-processor failed: unexpected EOF
2017/05/21 13:45:30 Builds completed. Waiting on interrupt barrier...
2017/05/21 13:45:30 machine readable: error-count []string{"1"}
2017/05/21 13:45:30 ui error: 
==> Some builds didn't complete successfully and had errors:
2017/05/21 13:45:30 machine readable: amazon-ebs,error []string{"1 error(s) occurred:\n\n* Post-processor failed: unexpected EOF"}
2017/05/21 13:45:30 ui error: --> amazon-ebs: 1 error(s) occurred:

* Post-processor failed: unexpected EOF
2017/05/21 13:45:30 ui: 
==> Builds finished but no artifacts were created.
2017/05/21 13:45:30 waiting for all plugin processes to complete...
Build 'amazon-ebs' errored: 1 error(s) occurred:

* Post-processor failed: unexpected EOF

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: 1 error(s) occurred:

* Post-processor failed: unexpected EOF

==> Builds finished but no artifacts were created.
2017/05/21 13:45:30 /usr/bin/hpacker: plugin process exited

NOTE: hpacker is the packer binary with different name.

Let me know if anything else is required.

Thx,
Sandeep

**Comment by wata727** [comment]
Thank you for the detailed report :)
Looking at the debug log, it seems that describing AMI lists has failed.

What kind of credentials do you use? (e.g. static credentials in template, environment variables, shared credentials, IAM role etc.) In addition, what kinds of operations are permitted by credentials? This plugin requires permission to `DescribeImages`, `DeregisterImage` and `DeleteSnapshot`.

**Comment by awscodedeploy** [comment]
Hi,

EC2 instance on which packer is running am IAM role[Instance Profile] is attached and this IAM role is having admin privileges. Even i have checked all above mentioned aws permissions using aws cli, i was to describe images, deregister and delete/describe snapshots.

Query:
- does amazon-ami-management plugin automatically get the temporary AWS credentials from instance meta data? i think it is not taking....as i have tried it by defining the access and secret key in the post proccessor amazon-ami-management section and it worked.

Could you please check at your side, if this works with AWS IAM role attached with instance, as i don't want to have AWS credentials on file system.

Thx,
Sandeep

**Comment by awscodedeploy** [comment]
Also, if this does not at your side using EC2 instance profile(IAM Role), could you please let me know about the fix for same.

Thx,
Sandeep

**Comment by awscodedeploy** [comment]
**Using aws access and secret keys:**
==> amazon-ebs: Running post-processor: amazon-ami-management
2017/05/21 15:25:27 packer-post-processor-amazon-ami-management: 2017/05/21 15:25:27 Running Amazon AMI Management post-processor
2017/05/21 15:25:27 packer-post-processor-amazon-ami-management: 2017/05/21 15:25:27 Creating AWS session
2017/05/21 15:25:27 packer-post-processor-amazon-ami-management: 2017/05/21 15:25:27 Describing images for generation management
2017/05/21 15:25:30 packer-post-processor-amazon-ami-management: 2017/05/21 15:25:30 Deleting old images...
    amazon-ebs (amazon-ami-management): Deleting image: ami-821d9ae1
2017/05/21 15:25:30 ui:     amazon-ebs (amazon-ami-management): Deleting image: ami-821d9ae1
2017/05/21 15:25:30 packer-post-processor-amazon-ami-management: 2017/05/21 15:25:30 Deleting image AMI (ami-821d9ae1)
2017/05/21 15:25:30 packer-post-processor-amazon-ami-management: 2017/05/21 15:25:30 Deleting snapshot related to AMI (ami-821d9ae1)
2017/05/21 15:25:30 packer-post-processor-amazon-ami-management: 2017/05/21 15:25:30 Deleting snapshot (snap-0728e4c9b56303f71) related to AMI (ami-821d9ae1)

Thx

**Comment by ankitkl** [comment]
@wata727 : Do you get any chance to look into it.

**Comment by jkumar19** [comment]
Thanks Kazuma. This is really awesome plugin and save me to implement the logic from scratch. As you are the expert of this plugin can you help me to add support for EC2 instance (Role based) authentication? I will highly appreciate it.

**Comment by wata727** [comment]
Hi there.
I have been release v0.2.0. This version includes EC2RoleProvider support. Please try it.

**Comment by jkumar19** [comment]
Thanks so much Kazuma. I highly appreciate it.

**Comment by awscodedeploy** [comment]
Thanks a ton Kazuma, this really helps us to manage the credentials in very
clean way.

**Comment by awscodedeploy** [comment]
Just one quick question Kazuma, while defining post processor with
amazon-ami-management [v.0.2.0] plugin, can we define our own IAM Role
which will be assumed by plugin to manage AMI's (if yes what would be that
option like region or keep_releases etc..) or it will only look for
temporary credentials in ec2 metadata? please confirm

Why i am asking this, if it will only look for the instance ec2 metadata
for temporary credentials, then AMI's will only managed for single account
in which that EC2 instance will be running(where packer is running), but if
we are sharing AMI's with different AWS accounts (which is supported by
packer out-of-box via ami_users), then we will not be able to manage AMI's
in that case, i am hoping that now this will be in your radar and will be
available soon in next release.

Once all these features will be available in this plugin, it will really
help others to accept packer widely.

Thanks and Regards,
Sandeep
