### ISSUE TITLE
Remove only unused AMIs

### ISSUE THREAD

**Issue by nitrocode** [wata727/packer-post-processor-amazon-ami-management#30]
Yesterday my team brought up another interesting issue where the packer post processor could potentially remove an AMI that an Auto Scaling Group's Launch Configuration is currently using. If that AMI gets deregistered and we scale up, the ASG will not be able to create an instance based on that AMI.

Would it be conceivable to have an additional option to only remove if the AMI is unused e.g. `remove_if_unused` ?

This doesn't seem possible to see in the AWS Console but there is a `Reservations` key in the `describe-images` awscli command which shows you where the AMI is used. If it is empty, it is unused [according to cloud conformity](https://www.cloudconformity.com/conformity-rules/EC2/unused-ami.html).

```
aws ec2 describe-images \
	--region us-east-1 \
	--image-ids ami-3f708e52 \
	--query 'Images[*].BlockDeviceMappings[*].Ebs.SnapshotId'
```

That can be piped into `jq '.Reservations[].Instances[].InstanceId'` to get a list of instance ids.

Lately I've been waffling between the [CloudCustodian](https://github.com/cloud-custodian/cloud-custodian/issues/2363#issuecomment-442631466) project, this project, and creating a custom lambda. For now, I think only the last could currently solve this issue.

**Comment by wata727** [comment]
I'm surprised to know that. I misunderstood that the post processor will return an error if the AMI to remove is used elsewhere.
I guess that the current behavior is a bug. Regardless of conditions, the post processor should not remove AMIs that are already in use. Perhaps this issue will be fixed by changing the default behavior.

**Comment by nitrocode** [comment]
Thanks @wata727! I'll compile the post processor for now. Any timeline on a new release?

**Comment by wata727** [comment]
@nitrocode Yeah, I'm planning to release the new version soon.

**Comment by wata727** [comment]
Released https://github.com/wata727/packer-post-processor-amazon-ami-management/releases/tag/v0.6.0
