### ISSUE TITLE
Can't get it to work in CodeBuild - any suggestions

### ISSUE THREAD

**Issue by kgorskowski** [wata727/packer-post-processor-amazon-ami-management#39]
Implementing a packer AMI pipeline in CodePipeline/CodeBuild and I am trying to implement your ami management plugin (don't want to introduce yet another lambda)
Packer 1.3.5
plugin: latest (0.6.1)
Installing via your script on Ubuntu 14 based build.
Installation works but it seems that somehow packer spaws the process in a way that doesn't work
```
Failed to initialize build 'amazon-ebs': error initializing post-processor 'amazon-ami-management': fork/exec /root/.packer.d/plugins/packer-post-processor-amazon-ami-management: no such file or directory 
```
Do you have any ideas where the problem might be? Tried chaining the command differently with no success. Local tests on Ubuntu/Mac worked perfectly.
Thanks!

**Comment by kgorskowski** [comment]
Can confirm that the plugin version 0.6.0 works in codebuild, will use that for now, thanks for the hint

**Comment by wata727** [comment]
v0.6.2 released
https://github.com/wata727/packer-post-processor-amazon-ami-management/releases/tag/v0.6.2
