### ISSUE TITLE
Can't pull credentials when running in a container

### ISSUE THREAD

**Issue by akdor1154** [wata727/packer-post-processor-amazon-ami-management#6]
Running in an ECS container, the Task Role and Instance Role should be able to be automatically assumed by this plugin (they work for example with the amazon-ebs builder).

However, relying on this yields a NoCredentialsError from the aws sdk lib.

**Comment by wata727** [comment]
Hi @akdor1154 
Maybe it should work normally. Can you show me the detailed log? (like `PACKER_LOG=1`)
Also, what version of plugin do you use? `0.1.1` is known to have problems.

**Comment by akdor1154** [comment]
I'm not sure I'll be able to get a log sorry, our build pipeline is crap and it makes it quite hard for me to get information from. I reckon I know where the problem is though - it looks like you are getting credentials from the EnvProvider, SharedConfigProvider, and EC2Metadata provider. However the ECS credentials system uses a different provider to these.
When using boto (the python sdk), it handles credentials automatically and you don't have to specify which providers to use. This means when they add a new one (e.g. the ecs credentials provider) you get it automatically. Is there any similar mode of use for the go sdk? It would fix this and probably save you effort in future as well. :)
